### ISSUE TITLE
Loading Example Data

### ISSUE THREAD

**Issue by rquin039** [mccoy-lab/rhapsodi#1]
Hello!
I'm trying to use this software for my project and was following the vignette posted. While following your vignette and when trying to follow along in the section titled "Example Data: 0/1/NA encoded" I was trying to load the data titled "sim01NA42.rda" which I had previously downloaded from the data folder. However when checking the data it shows that the data does not load correctly and it is being loaded as a character. The following is the code: 
Output:
> sim01NA42<- load(“data/sim01NA42.rda”)
> head(sim01NA42)
[1] “sim01NA42"

What can be done to fix this?

**Comment by andrew-bortvin** [comment]
Hello! When using the `load()` function, you should not assign your output to a variable; `load()` will automatically import data and assign variable names. Running the following correctly reads in your data:

>load("data/sim01NA42.rda")
head(sim01NA42)

Results in: 

>   positions gam1_ gam2_ gam3_ gam4_ gam5_ gam6_ gam7_ gam8_ gam9_ gam10_ gam11_ gam12_ gam13_ gam14_ gam15_ gam16_
1         3    NA    NA    NA     0    NA    NA    NA    NA     1     NA     NA      0     NA     NA      1     NA
2         4    NA    NA    NA    NA     1    NA    NA    NA    NA     NA     NA     NA     NA     NA     NA     NA
3         5    NA    NA    NA    NA    NA    NA     0    NA    NA     NA     NA     NA      0     NA     NA     NA
